[package]
name = "os"
version = "0.1.0"
authors = ["Serentty"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"


[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = { version = "0.9.11", features = ["vga_320x200"] }

[profile.dev]
opt-level = "z"
overflow-checks = true
lto = true
incremental = true
debug = true

